apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

namespace: observability-stg

patches:
  - target:
      kind: Namespace
      name: observability
    patch: |-
      - op: replace
        path: /metadata/name
        value: observability-stg

  - target:
      kind: HelmRelease
      name: kube-prometheus-stack
    patch: |-
      - op: replace
        path: /spec/values/prometheus/prometheusSpec/retention
        value: 7d
      - op: replace
        path: /spec/values/prometheus/prometheusSpec/storageSpec/volumeClaimTemplate/spec/resources/requests/storage
        value: 20Gi
      - op: replace
        path: /spec/values/grafana/replicas
        value: 1

  - target:
      kind: HelmRelease
      name: loki
    patch: |-
      - op: replace
        path: /spec/values/loki/storage/bucketNames/chunks
        value: stg-loki-chunks
      - op: replace
        path: /spec/values/loki/storage/bucketNames/ruler
        value: stg-loki-ruler
